In [1]:
import numpy as np

In [2]:
np.sqrt(10)

3.1622776601683795

In [4]:
print('Minimum ', np.amin([25,30,57,18]))

Minimum  18


In [6]:
print('Minimum ', np.amax([25,30,57,18]))

Minimum  57


In [7]:
np.ceil(29.5)

30.0

In [8]:
np.ceil(np.sqrt(10))

4.0

In [9]:
np.ceil(np.sum(np.sqrt([5,10,15])))

10.0

In [10]:
np.array([5,19,13])

array([ 5, 19, 13])

In [11]:
type([5,19,13])

list

In [12]:
#Two Dimension

a= np.array([[1,2],[3,4],[4,5]])

In [13]:
print("Type - ", a.dtype)
print('\n', '*' * 30)
print('\n',a)

Type -  int32

 ******************************

 [[1 2]
 [3 4]
 [4 5]]


In [16]:
#dtype conversion

np.array([1,2,3], dtype= float)

array([1., 2., 3.])

In [18]:
#Creating array using mat(matrix)

np.array(np.mat('123 ; 345'))

array([[123],
       [345]])

In [19]:
#Convert a list into an array

a= [1,2]

c= np.array(a)

print(c)

[1 2]


In [20]:
#Copy array into other
b= np.array(c)

print(b)

[1 2]


In [2]:
import numpy as np

In [3]:
my_mat= [[1,2,3],[4,5,6],[7,8,9]]

mat= np.array(my_mat)

print("Type/Class of this object:", type(mat))

print("Here is the matrix\n-----------------\n",mat,"\n------------------")

print("Dimension of this matrix: ", mat.ndim, sep='') #ndim gives the dimension, 2 for a matrix 1 for a vector

print("Size of this matrix: ", mat.size, sep='') #size gives the total number of elements.
print("Shape of this matrix: ", mat.shape) 
print("Data type of this matrix: ", mat.dtype)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
-----------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
------------------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix:  (3, 3)
Data type of this matrix:  int32


In [5]:
#arrange and linspace

list(range(2,10.5,.4)) # don't work with python range

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
a= np.arange(2,10.5,.4)
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [8]:
#Reverse order

a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [10]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,0,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5]


In [11]:
print("Linearly spaced numbers between 1 and 5\n-------------------------")
print(np.linspace(10,40,5))

Linearly spaced numbers between 1 and 5
-------------------------
[10.  17.5 25.  32.5 40. ]


In [13]:
#Include end point and check space between the points
#By default end pont= True
#By default retstep= False
#np.linspace(2.0,3.0, num=4, endpoint= False, retstep= True)
np.linspace(2.0,3.0, num=4, endpoint= True, retstep= False)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [14]:
print(np.linspace(4.5678, 25.9865, 39, retstep= True))

(array([ 4.5678 ,  5.13145,  5.6951 ,  6.25875,  6.8224 ,  7.38605,
        7.9497 ,  8.51335,  9.077  ,  9.64065, 10.2043 , 10.76795,
       11.3316 , 11.89525, 12.4589 , 13.02255, 13.5862 , 14.14985,
       14.7135 , 15.27715, 15.8408 , 16.40445, 16.9681 , 17.53175,
       18.0954 , 18.65905, 19.2227 , 19.78635, 20.35   , 20.91365,
       21.4773 , 22.04095, 22.6046 , 23.16825, 23.7319 , 24.29555,
       24.8592 , 25.42285, 25.9865 ]), 0.56365)


In [15]:
#Create Matrix

print("Vector of zeros\n---------------------------------")
print(np.zeros(5))

Vector of zeros
---------------------------------
[0. 0. 0. 0. 0.]


In [16]:
print("Matrix of zeros\n---------------------------------")

print(np.zeros((5,6))) #Notice Tuples

Matrix of zeros
---------------------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
print("Matrix of ones\n---------------------------------")

print(np.ones((5,8)))

Matrix of ones
---------------------------------
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [18]:
print("Matrix of 5's\n---------------------------------")

print(5*np.ones((2,3)))

Matrix of 5's
---------------------------------
[[5. 5. 5.]
 [5. 5. 5.]]


In [20]:
#Construct diagpnal Matrix
x= np.arange(30).reshape(6,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [21]:
#Random Number generation
np.random.seed(6)

print("Random number generation (from uniform distribution)")

print(np.random.rand(10,6))

Random number generation (from uniform distribution)
[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [24]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(10,3)) #randn Negative data

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.96813764  0.16706673  0.11660197]
 [-0.68225732 -1.91402115 -0.13990231]
 [ 0.11492459 -0.39500464 -0.95331626]
 [-1.07282736 -0.48444561  1.36293786]
 [ 0.15268777 -1.6326206   0.64330145]
 [-0.44789505  2.33903423 -0.31332286]
 [-0.05961756  0.19416833  0.2868793 ]
 [ 0.05185969  0.05155094 -0.21958725]
 [-0.5532565  -0.37391087 -1.18441686]
 [-0.52817318 -0.66353389 -0.43373648]]


In [25]:
print("Random integer vector:",np.random.randint(5,20,10)) #randint(low, high, #of samples to be drawn)


Random integer vector: [ 6 12  6 11 15 13  6 10 14 17]


In [26]:
print("\nRandom ineger matrix")
print(np.random.randint(1,3000,(6,7)))


Random ineger matrix
[[2078 1283  140 1771 1129  808 1442]
 [  68 1205 2720 1639  965 1046  263]
 [1801  694 2282 1950 2748 1924 2613]
 [1911  573   35  392 2096 2711 2817]
 [1510 1199 1662  665 2462  681 1945]
 [2247 1135 2054 2027 1804 1963  908]]


In [27]:
#Numpy Condition
emp_salary= np.random.randint(8,70,10)
emp_salary

array([52, 58,  9, 15, 58, 15, 40, 13, 69, 13])

In [29]:
#Set minimum and maximum salary using min and max

np.clip(emp_salary, a_min=20, a_max=50)

array([50, 50, 20, 20, 50, 20, 40, 20, 50, 20])

In [36]:
#If you want to find actual salary which are less than or greater than some salary use np.where. np.where gives index details

print(np.where(emp_salary >20))




(array([0, 1, 4, 6, 8], dtype=int64),)


In [34]:
#if you want to see actual data use index.

emp_salary[[0,2,4]]

array([52,  9, 58])

In [37]:
#Reshaping other ways

import numpy as np
from numpy.random import randint as ri

a= ri(1,99,30)
a

array([ 9, 46, 75,  4, 37, 40, 67, 43, 23, 82, 51, 84, 84, 19, 78, 48, 66,
       97, 70, 45, 21, 17, 85, 55, 50, 73, 83, 85, 20, 28])

In [38]:
b= a.reshape(2,3,5)
b

array([[[ 9, 46, 75,  4, 37],
        [40, 67, 43, 23, 82],
        [51, 84, 84, 19, 78]],

       [[48, 66, 97, 70, 45],
        [21, 17, 85, 55, 50],
        [73, 83, 85, 20, 28]]])

In [39]:
c= a.reshape(6,5)
c

array([[ 9, 46, 75,  4, 37],
       [40, 67, 43, 23, 82],
       [51, 84, 84, 19, 78],
       [48, 66, 97, 70, 45],
       [21, 17, 85, 55, 50],
       [73, 83, 85, 20, 28]])

In [41]:
print("Min of a:", c.min())
print("Max of a:", c.max())


Min of a: 4
Max of a: 97


In [42]:
np.mean(c)

52.833333333333336

In [43]:
M= ri(1,100,25).reshape(5,5)

print("\n5x5 Matrix of random integers \n",'-'*50,"\n",M)

print("\nHere is the sorted Matrix along each row\n",'-'*50,"\n",np.sort(M))

print("\nHere is the sorted Matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0))


5x5 Matrix of random integers 
 -------------------------------------------------- 
 [[ 6 85 61  6 16]
 [38  7 28 80 56]
 [24 84 36  3 99]
 [82 55 24 64 59]
 [20 19 72 27 58]]

Here is the sorted Matrix along each row
 -------------------------------------------------- 
 [[ 6  6 16 61 85]
 [ 7 28 38 56 80]
 [ 3 24 36 84 99]
 [24 55 59 64 82]
 [19 20 27 58 72]]

Here is the sorted Matrix along each column
 -------------------------------------------------- 
 [[ 6  7 24  3 16]
 [20 19 28  6 56]
 [24 55 36 27 58]
 [38 84 61 64 59]
 [82 85 72 80 99]]


In [2]:
import numpy as np

In [3]:
arr= np.arange(13,30)
print("Array:", arr)

Array: [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [4]:
print("Element of 7th index is:", arr[7])

Element of 7th index is: 20


In [6]:
print("Elements from 3rd to 5th index are:", arr[3:6])

Elements from 3rd to 5th index are: [16 17 18]


In [8]:
print("Elements upto 4th index are:", arr[4:])
abc= arr[4:]

Elements upto 4th index are: [17 18 19 20 21 22 23 24 25 26 27 28 29]


In [9]:
abc

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
arr

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
print("Elements from last backwards are:", arr[-1::-2])

Elements from last backwards are: [29 27 25 23 21 19 17 15 13]


In [18]:
print("7 Elemnets from last backwards are:", arr[-1:-8:-1])

7 Elemnets from last backwards are: [29 28 27 26 25 24 23]


In [19]:
arr= np.arange(0,21,2)
print("New array:", arr)

New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [21]:
print("Elements at 2nd, 4th and 9th index are:", arr[[2,4,9]])

Elements at 2nd, 4th and 9th index are: [ 4  8 18]


In [22]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

mat= np.array(my_mat)

mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
print("Double bracket indexing\n------------------------------")
print("Element in row index 1 and column index 2:", mat[1][2])

Double bracket indexing
------------------------------
Element in row index 1 and column index 2: 6


In [24]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
print("Entire row at index 2:", mat[2])
print("\nEntire colum at index 3: \n", mat[:,1:])

Entire row at index 2: [7 8 9]

Entire colum at index 3: 
 [[2 3]
 [5 6]
 [8 9]]


In [26]:
print("\nSusetting and sub-matrices\n---------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:2,1:2])


Susetting and sub-matrices
---------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[5]]


In [27]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
print("", mat[0:2,[1,2]])

 [[2 3]
 [5 6]]


In [29]:
#Update Matrix
print("Oroginal Matrix \n\n", mat)

Oroginal Matrix 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
mat[0,1]= 35
mat

array([[ 1, 35,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
mat[1,0]= 100
mat

array([[  1,  35,   3],
       [100,   5,   6],
       [  7,   8,   9]])

In [34]:
import numpy as np
from numpy.random import randint as ri

In [35]:
#Subseting

mat= np.array(ri(10,100,15)).reshape(3,5)

print("Matrix of random 2 digits number\n-------------------\n", mat)

Matrix of random 2 digits number
-------------------
 [[97 84 84 29 94]
 [36 63 45 15 17]
 [29 57 63 32 52]]


In [36]:
print("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [97 84 84 94 63 57 63 52]


In [37]:
mat>50

array([[ True,  True,  True, False,  True],
       [False,  True, False, False, False],
       [False,  True,  True, False,  True]])

In [39]:
print(np.where(mat==94))

(array([0], dtype=int64), array([4], dtype=int64))


In [42]:
#You can also use np.where to return some data based on condition

age= 70
np.where(age >65,'Retired', 'Still Working')

array('Retired', dtype='<U13')

In [43]:
#Universal Functions

mat1= np.array(ri(1,10,9).reshape(3,3))
mat2= np.array(ri(1,10,9).reshape(3,3))

print("\nFirst matrix of random single-digit numbers\n-------------------------------------\n", mat1)
print("\nSecond matrix of random single-digit numbers\n-------------------------------------\n", mat2)


First matrix of random single-digit numbers
-------------------------------------
 [[8 1 8]
 [5 1 5]
 [6 4 4]]

Second matrix of random single-digit numbers
-------------------------------------
 [[7 7 4]
 [5 7 5]
 [1 7 1]]


In [44]:
print("\nAddition\n-------------------\n", mat1+mat2)
print("\nMultiplication\n-------------------\n", mat1*mat2)


Addition
-------------------
 [[15  8 12]
 [10  8 10]
 [ 7 11  5]]

Multiplication
-------------------
 [[56  7 32]
 [25  7 25]
 [ 6 28  4]]


In [47]:
print("\nDivision\n----------------------------------------------\n",mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n--------------------------------------\n", 3*mat1 - 2*mat2)


Division
----------------------------------------------
 [[1.14285714 0.14285714 2.        ]
 [1.         0.14285714 1.        ]
 [6.         0.57142857 4.        ]]

Linear combination: 3*A - 2*B
--------------------------------------
 [[ 10 -11  16]
 [  5 -11   5]
 [ 16  -2  10]]


In [48]:
start= np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [49]:
#Create a rank 1 ndarray with 3 values

add_rows = np.array([[1,0,2]])
add_rows

array([[1, 0, 2]])

In [51]:
y= start+add_rows
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [52]:
new_row= add_rows.T
new_row

array([[1],
       [0],
       [2]])

In [53]:
test= new_row+start
test

array([[1., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.]])

In [55]:
#Create an ndarray which is 4 X 1 to broadcast across columns

add_cols= np.array([[0,1,2,3]])

add_cols= add_cols.T

add_cols

array([[0],
       [1],
       [2],
       [3]])

In [56]:
#Array Math
mat1= np.array(ri(1,10,9).reshape(3,3))
mat2= np.array(ri(1,10,9).reshape(3,3))

print("\nFirst matrix of random single-digit numbers\n-------------------------------------\n", mat1)
print("\nSecond matrix of random single-digit numbers\n-------------------------------------\n", mat2)


First matrix of random single-digit numbers
-------------------------------------
 [[3 1 9]
 [2 7 6]
 [7 5 4]]

Second matrix of random single-digit numbers
-------------------------------------
 [[6 1 3]
 [7 6 8]
 [5 3 4]]


In [57]:
print("\nSq-root of 1st Matrix using np\n----------------------------------\n", np.sqrt(mat1))


Sq-root of 1st Matrix using np
----------------------------------
 [[1.73205081 1.         3.        ]
 [1.41421356 2.64575131 2.44948974]
 [2.64575131 2.23606798 2.        ]]


In [58]:
print("\nSquare of 1st matrix using np\n--------------------------------\n", np.square(mat1))


Square of 1st matrix using np
--------------------------------
 [[ 9  1 81]
 [ 4 49 36]
 [49 25 16]]
