In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
titanic_train= pd.read_csv(r"C:\Users\singh\Files-main\titanic_train.csv")

In [5]:
titanic_train

Unnamed: 0  PassengerId  Survived  Pclass  \
0             0            1         0       3   
1             1            2         1       1   
2             2            3         1       3   
3             3            4         1       1   
4             4            5         0       3   
..          ...          ...       ...     ...   
886         886          887         0       2   
887         887          888         1       1   
888         888          889         0       3   
889         889          890         1       1   
890         890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 13 columns]

In [6]:
titanic_train['Survived'].unique() #to check unique value of any column

array([0, 1], dtype=int64)

In [7]:
#How to rename categories using pandas menthod.

new_survived= pd.Categorical(titanic_train['Survived'])

new_survived= new_survived.rename_categories(['Died','Survived'])

new_survived.describe()

counts     freqs
categories                  
Died           549  0.616162
Survived       342  0.383838

In [8]:
titanic_train['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [9]:
new_Pclass= pd.Categorical(titanic_train['Pclass'],
                           ordered= True)

new_Pclass= new_Pclass.rename_categories(['Class1','Class2','Class3'])

new_Pclass.describe()

counts     freqs
categories                  
Class1         216  0.242424
Class2         184  0.206510
Class3         491  0.551066

In [10]:
titanic_train['Pclass']= new_Pclass

In [12]:
titanic_train.head()

Unnamed: 0  PassengerId  Survived  Pclass  \
0           0            1         0  Class3   
1           1            2         1  Class1   
2           2            3         1  Class3   
3           3            4         1  Class1   
4           4            5         0  Class3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [13]:
#Find all the passengers who's age is missing.

missing= np.where(titanic_train['Age'].isnull()==True)

missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [14]:
titanic_train.loc[missing]

Unnamed: 0  PassengerId  Survived  Pclass  \
5             5            6         0  Class3   
17           17           18         1  Class2   
19           19           20         1  Class3   
26           26           27         0  Class3   
28           28           29         1  Class3   
..          ...          ...       ...     ...   
859         859          860         0  Class3   
863         863          864         0  Class3   
868         868          869         0  Class3   
878         878          879         0  Class3   
888         888          889         0  Class3   

                                         Name     Sex  Age  SibSp  Parch  \
5                            Moran, Mr. James    male  NaN      0      0   
17               Williams, Mr. Charles Eugene    male  NaN      0      0   
19                    Masselmani, Mrs. Fatima  female  NaN      0      0   
26                    Emir, Mr. Farred Chehab    male  NaN      0      0   
28              O'Dwyer, Miss. Ellen "Nellie"  female  NaN      0      0   
..                                        ...     ...  ...    ...    ...   
859                          Razi, Mr. Raihed    male  NaN      0      0   
863         Sage, Miss. Dorothy Edith "Dolly"  female  NaN      8      2   
868               van Melkebeke, Mr. Philemon    male  NaN      0      0   
878                        Laleff, Mr. Kristo    male  NaN      0      0   
888  Johnston, Miss. Catherine Helen "Carrie"  female  NaN      1      2   

         Ticket     Fare Cabin Embarked  
5        330877   8.4583   NaN        Q  
17       244373  13.0000   NaN        S  
19         2649   7.2250   NaN        C  
26         2631   7.2250   NaN        C  
28       330959   7.8792   NaN        Q  
..          ...      ...   ...      ...  
859        2629   7.2292   NaN        C  
863    CA. 2343  69.5500   NaN        S  
868      345777   9.5000   NaN        S  
878      349217   7.8958   NaN        S  
888  W./C. 6607  23.4500   NaN        S  

[177 rows x 13 columns]

In [15]:
#Find the maximum fare.

index= np.where(titanic_train['Fare']== max(titanic_train['Fare']))

index

(array([258, 679, 737], dtype=int64),)

In [17]:
titanic_train.loc[index]

Unnamed: 0  PassengerId  Survived  Pclass  \
258         258          259         1  Class1   
679         679          680         1  Class1   
737         737          738         1  Class1   

                                   Name     Sex   Age  SibSp  Parch    Ticket  \
258                    Ward, Miss. Anna  female  35.0      0      0  PC 17755   
679  Cardeza, Mr. Thomas Drake Martinez    male  36.0      0      1  PC 17755   
737              Lesurer, Mr. Gustave J    male  35.0      0      0  PC 17755   

         Fare        Cabin Embarked  
258  512.3292          NaN        C  
679  512.3292  B51 B53 B55        C  
737  512.3292         B101        C

In [19]:
#Find the family who has highest member.

titanic_train['Family']= titanic_train['SibSp']+ titanic_train['Parch']

most_family= np.where(titanic_train['Family']== max(titanic_train['Family']))

titanic_train.loc[most_family]

Unnamed: 0  PassengerId  Survived  Pclass  \
159         159          160         0  Class3   
180         180          181         0  Class3   
201         201          202         0  Class3   
324         324          325         0  Class3   
792         792          793         0  Class3   
846         846          847         0  Class3   
863         863          864         0  Class3   

                                  Name     Sex  Age  SibSp  Parch    Ticket  \
159         Sage, Master. Thomas Henry    male  NaN      8      2  CA. 2343   
180       Sage, Miss. Constance Gladys  female  NaN      8      2  CA. 2343   
201                Sage, Mr. Frederick    male  NaN      8      2  CA. 2343   
324           Sage, Mr. George John Jr    male  NaN      8      2  CA. 2343   
792            Sage, Miss. Stella Anna  female  NaN      8      2  CA. 2343   
846           Sage, Mr. Douglas Bullen    male  NaN      8      2  CA. 2343   
863  Sage, Miss. Dorothy Edith "Dolly"  female  NaN      8      2  CA. 2343   

      Fare Cabin Embarked  Family  
159  69.55   NaN        S      10  
180  69.55   NaN        S      10  
201  69.55   NaN        S      10  
324  69.55   NaN        S      10  
792  69.55   NaN        S      10  
846  69.55   NaN        S      10  
863  69.55   NaN        S      10